apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeodm-deployment
spec:
  replicas: REPNUM 
  selector:
    matchLabels:
      app: nodeodm
  template:
    metadata:
      labels:
        app: nodeodm
    spec:
      containers:
        - name: nodeodm
          image: opendronemap/nodeodm:gpu
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: data-volume
              mountPath: /cm/local
      volumes:
        - name: data-volume
          emptyDir: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterodm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clusterodm
  template:
    metadata:
      labels:
        app: clusterodm
    spec:
      containers:
        - name: clusterodm
          image: opendronemap/clusterodm
          ports:
            - containerPort: 3000
            - containerPort: 10000
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: nodeodm-service
spec:
  type: NodePort
  selector:
    app: nodeodm
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000

---

apiVersion: v1
kind: Service
metadata:
  name: clusterodm-service
spec:
  type: LoadBalancer
  externalIPs:
    - EXTERNALIPADDRESS
  ports:
    - name: port-3000
      port: 3000
      targetPort: 3000
    - name: port-10000
      port: 10000
      targetPort: 10000
    - name: port-8080
      port: 8080
      targetPort: 8080
  selector:
    app: clusterodm
